# Configuration file for the example Python application# This file is used to configure various aspects of the application, including logging, database connections,
# API settings, and feature flags. It is structured in a standard INI format, which can be easily read and modified.
# The sections are clearly defined, and each setting is documented to provide clarity on its purpose and usage.
# The application uses this configuration to initialize components and manage runtime behavior. 
# Ensure to keep this file secure, especially sensitive information like database credentials and encryption keys.
# Comments are provided to explain each section and setting, making it easier for developers to understand and maintain the configuration.
# The configuration file is divided into several sections, each serving a specific purpose.
# The sections include:
# - [logging]: Configuration for logging behavior, including log level, file output, and console output.
# - [database]: Settings for connecting to a PostgreSQL database using SQLAlchemy, including connection parameters, pooling options, and SSL settings.  
# - [api]: Configuration for API interactions, including base URL, timeout settings, and headers.
# - [features]: Feature flags to enable or disable specific functionalities within the application. 
# - [security]: Security-related settings, such as encryption keys and token expiry times.


##########################################################################################################
# Configuration for the application logging - START 
############################################################################################################
# This section defines the logging  parameters for the application using standard Python logging configuration.
# It includes settings for the logger name, log level, log file, format, and whether to log to the console.
[logging]
loggerName = ConnectorExample
level = DEBUG
log_file = example.log
format = %(asctime)s - %(levelname)s - %(message)s
log_to_console = true
autodebug = true
##########################################################################################################
# Configuration for the application logging - END 
############################################################################################################




##########################################################################################################
# Configuration for the database connection - START 
############################################################################################################
# This section defines the connection parameters for a PostgreSQL database as an example using SQLAlchemy.
[database]
# driver: Database driver to use for the connection
driver = postgresql+psycopg
# host: Hostname or IP address of the database server
host = localhost    
# port: Port number for the database server
port = 5432
# user: Username for the database connection
user = <<DB User>>
# password: Password for the database connection
password = <<DB Password>>
# database: Name of the database to connect to
database = postgres
# client_encoding: Character encoding for the database connection
client_encoding = utf8

# sslmode: SSL mode for the database connection.
# Options include disable, allow, prefer, require, verify-ca, verify-full
# prefer means the connection will use SSL if available, but will not fail if SSL is not available.
sslmode = prefer 

# application_name: Name of the application connecting to the database
application_name = ConnectorApp 

# connect_timeout: Timeout for establishing a connection in seconds
connect_timeout = 10 

# Database transaction isolation level.
# isolation_level: READ_COMMITTED - Prevent dirty reads. This is the default isolation level. 
# Other options include READ_UNCOMMITTED (Allows dirty reads), 
#                       REPEATABLE_READ (Ensures consistency within a transaction),  
#                       SERIALIZABLE (The strictest level, preventing phantom reads), 
#                       AUTOCOMMIT (No transaction, each statement is a transaction)
isolation_level = READ_COMMITTED 

# pool_reset_on_return: Set connection reset behavior. This is applicable when connection is returned to the pool.
# 'rollback' resets the connection to a clean state, while 'commit' leaves it in the last committed state.
# 'rollback' is generally safer as it avoids potential issues with uncommitted changes.
# Default is 'rollback', can be set to 'commit' or 'rollback'
pool_reset_on_return = rollback 

# Database Connection Pooling options for managing database connections. These are examples for PostgreSQL with SQLAlchemy
# pool_size: Maintain NN persistent connections
pool_size=10           
# max_overflow: Allow up to NN extra connections during peak
max_overflow=5         
# pool_recycle: Recycle connections NNNN seconds, one hour = 3600 seconds
pool_recycle=3600      
# pool_timeout: Wait up to NN seconds for a connection
pool_timeout=30        
# pool_pre_ping: Enables a health check before using a connection, ensuring it is still valid.
pool_pre_ping=True     
# pool_use_lifo: When set to True, it enables a Last-In, First-Out (LIFO) strategy, meaning the most recently returned connection to the pool is the next one to be used. This can be beneficial in scenarios with fluctuating load, as it keeps fewer connections open for extended periods, potentially reducing idle connections on the database server.
pool_use_lifo=True     
# echo_pool: When set to True, it generates a very high number of log lines. Set to false in production to avoid performance overhead unless required for debugging.
echo_pool = true       
# echo: When set to True, it enables logging of all SQL statements issued to the database. Set to false in production to avoid performance overhead unless required for debugging.
echo = true            
##########################################################################################################
# Configuration for the database connection - END 
############################################################################################################




############################################################################################################ Configuration for the API interactions - START
# Configuration for apis - START
############################################################################################################
# This section defines the base URL, timeout settings, and headers for API interactions.
# It is used to configure how the application communicates with external APIs, including retry logic and request headers.
# The base URL is the root endpoint for the API, and the timeout settings control how long the application will wait for a response before timing out.
# The headers can include authentication tokens, content types, and other necessary information for the API requests.
# The API settings are crucial for ensuring reliable and efficient communication with external services.    
[External APIs Configuration]
external_api_message_queue = true
external_api_message_queue_db_url = sqlite:///./database/dbstore/apimessages.db
# Maximum Number of threads for processing external API requests
external_api_max_workers = 4
# Timeout for external API requests
external_api_workers_timeout = 30
# Maximum requests per worker thread for processing external API requests in each cycle
# this parameter defines the maximum number of API requests that each worker thread can handle in a single processing cycle.
# By limiting the number of requests per cycle, it helps to manage the load on the system and ensures that each thread can efficiently process its assigned tasks without being overwhelmed.
external_api_workers_max_load = 5
# Load distribution method for external API worker threads
# Options include RR = Round Robin, LL = Least Loaded, RND = Random
external_api_workers_load_distribution_method = LL
# Base URL for the example external API
#echo_api_base_url = https://jsonplaceholder.typicode.com/
echo_api_base_url = https://postman-echo.com
echo_api_route = post
echo_timeout = 15
echo_retries = 3
echo_bearer_token = ExampleToken
echo_throttling_interval = 900
echo_headers = {"User-Agent": "ExampleClient/1.0", "x-api-key": "reqres-free-v1"}
echo_default_api_json_payload = {"userId": 1, "id": 1, "title": "Sample Title", "body": "Sample Body"}
echo_payload_template_file = metadata/external_api_payload_template.json



########################################################################################################### Configuration for the API interactions - END 
# Configuration for apis - START
############################################################################################################




###########################################################################################################
# Configuration for feature flags - START
############################################################################################################
# This section defines feature flags to enable or disable specific functionalities within the application.
[features]
enable_feature_x = true
enable_feature_y = false    
enable_feature_z = true

###########################################################################################################
# Configuration for feature flags - END
############################################################################################################    




##########################################################################################################
# Configuration for security settings - START   
############################################################################################################
# This section defines security-related settings, such as encryption keys and token expiry times.
[security]  
encryption_key = my_secret_key
token_expiry = 3600
allowed_ips = 192.168.1.1, 192.168.1.2
##########################################################################################################
# Configuration for security settings - END 
############################################################################################################

