# CI360 settings  (Note access point name here for future reference)
ci360.gatewayHost  = insert-gatewayHost-here
ci360.tenantID = insert-tenantID-here
ci360.clientSecret = insert-clientSecret-here

# Task cache settings
task.expiresMinutes = 60
task.httpTimeoutSeconds = 5
task.httpRetries = 2

# Task SQL settings
task.sql.user = 
task.sql.pw = 
task.sql.jdbcURL = 
task.sql.taskTable             = agent.MD_TASK
task.sql.customPropertiesTable = agent.MD_TASK_CUSTOM_PROP

# Event SQL settings
event.sql.user = insert-sql.user-here
event.sql.pw = insert-sql.pw.here
event.sql.jdbcURL = insert-jdbcURL-here
event.sql.table   = agent.STREAMING_EVENTS
event.sql.poolSize = 5
event.sql.bufferSize = 100000
event.sql.secondsBetweenSubmits = 300

server.port=10089
