USE [CIDB]
GO

-- Check if schema exists, create if not
IF NOT EXISTS (
    SELECT 1
    FROM sys.schemas
    WHERE name = 'AGENT'
)
BEGIN
    EXEC('CREATE SCHEMA AGENT');
END


/****** Object:  Table [agent].[MD_TASK_CUSTOM_PROP]    Script Date: 02-06-2021 15:21:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'AGENT'
      AND TABLE_NAME = 'STREAMING_EVENTS'
)
BEGIN
	DROP TABLE AGENT.STREAMING_EVENTS
END
GO

CREATE TABLE [AGENT].STREAMING_EVENTS(
       AGENT_DTTM date NULL,
       EVENT_JSON nvarchar(max) NULL,
	   load_dttm DATETIMEOFFSET(2) NOT NULL CONSTRAINT DF_load_dttm1 DEFAULT(sysdatetimeoffset())
	   ) ON [PRIMARY]
GO

IF EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'AGENT'
      AND TABLE_NAME = 'MD_TASK'
)
BEGIN
	DROP TABLE AGENT.MD_TASK
END
GO
	   
CREATE TABLE [AGENT].[MD_TASK](
	[TASK_ID] [nvarchar](36) NULL,
	[TASK_NM] [nvarchar](60) NULL,
	[TASK_STATUS_CD] [nvarchar](20) NULL,
	[TASK_VERSION_ID] [nvarchar](36) NULL,
	[VALID_FROM_DTTM] [datetime2](3) NULL,
	[VALID_TO_DTTM] [datetime2](3) NULL,
	[TASK_DESC] [nvarchar](1332) NULL,
	[CREATED_USER_NM] [nvarchar](40) NULL,
	[OWNER_NM] [nvarchar](40) NULL,
	[LAST_PUBLISHED_DTTM] [datetime2](3) NULL,
	[TASK_TYPE_NM] [nvarchar](40) NULL,
	[SCHEDULED_FLG] [nchar](1) NULL,
	[RECURRING_SCHEDULE_FLG] [nchar](1) NULL,
	[TASK_DELIVERY_TYPE_NM] [nvarchar](60) NULL,
	[TASK_SUBTYPE_NM] [nvarchar](30) NULL,
	[ACTIVITY_FLG] [nchar](1) NULL,
	[CHANNEL_NM] [nvarchar](40) NULL,
	[DISPLAY_PRIORITY_NO] [int] NULL,
	[DELIVERY_CONFIG_TYPE_NM] [nvarchar](36) NULL,
	[ARBITRATION_METHOD_CD] [nvarchar](36) NULL,
	[TASK_CATEGORY_NM] [nvarchar](100) NULL,
	[TASK_CD] [nvarchar](60) NULL,
	[RTDM_FLG] [nchar](1) NULL,
	[EXPORT_TEMPLATE_FLG] [nchar](1) NULL,
	[SEND_NOTIFICATION_LOCALE_CD] [nvarchar](2) NULL,
	[MOBILE_APP_ID] [nvarchar](60) NULL,
	[MOBILE_APP_NM] [nvarchar](60) NULL,
	[IMPRESSIONS_LIFE_TIME_CNT] [int] NULL,
	[IMPRESSIONS_QTY_PERIOD_CNT] [int] NULL,
	[IMPRESSIONS_PER_SESSION_CNT] [int] NULL,
	[MAXIMUM_PERIOD_EXPRESSION_CNT] [int] NULL,
	[LIMIT_PERIOD_UNIT_CNT] [int] NULL,
	[PERIOD_TYPE_NM] [nvarchar](36) NULL,
	[RECURRENCE_FREQUENCY_CD] [nvarchar](36) NULL,
	[RECURRENCE_DAYS_OF_WEEK_TXT] [nvarchar](60) NULL,
	[RECURRENCE_MONTHLY_TYPE_NM] [nvarchar](36) NULL,
	[RECURRENCE_DAY_OF_MONTH_NO] [int] NULL,
	[RECURRENCE_DAY_OF_WEEK_TXT] [nvarchar](60) NULL,
	[RECURRENCE_DAY_OF_WK_ORDINAL_NO] [nvarchar](36) NULL,
	[REC_SCHEDULED_START_TM] [nvarchar](20) NULL,
	[REC_SCHEDULED_START_DTTM] [datetime2](3) NULL,
	[REC_SCHEDULED_END_DTTM] [datetime2](3) NULL,
	[TEMPLATE_ID] [nvarchar](36) NULL,
	[SUBJECT_LINE_TXT] [nvarchar](1332) NULL,
	[SCHEDULED_START_DTTM] [datetime2](3) NULL,
	[SCHEDULED_END_DTTM] [datetime2](3) NULL,
	load_dttm DATETIMEOFFSET(2) NOT NULL CONSTRAINT DF_load_dttm2 DEFAULT(sysdatetimeoffset())
) ON [PRIMARY]
GO

IF EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'AGENT'
      AND TABLE_NAME = 'MD_TASK_CUSTOM_PROP'
)
BEGIN
	DROP TABLE [AGENT].[MD_TASK_CUSTOM_PROP]
END
GO

CREATE TABLE [AGENT].[MD_TASK_CUSTOM_PROP](
	[TASK_ID] [nvarchar](36) NULL,
	[TASK_STATUS_CD] [nvarchar](36) NULL,
	[TASK_VERSION_ID] [nvarchar](36) NULL,
	[VALID_FROM_DTTM] [datetime2](3) NULL,
	[VALID_TO_DTTM] [datetime2](3) NULL,
	[PROPERTY_NM] [nvarchar](256) NULL,
	[PROPERTY_DATATYPE_NM] [nvarchar](256) NULL,
	[PROPERTY_VAL] [nvarchar](1332) NULL,
	load_dttm DATETIMEOFFSET(2) NOT NULL CONSTRAINT DF_load_dttm3 DEFAULT(sysdatetimeoffset())
) ON [PRIMARY]
GO


