apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-pvc-claim
spec:
  storageClassName: monitoring-and-logging-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem