/******************************************************************************/
/* Copyright(c)2025, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved. */
/* SPDX-License-Identifier: Apache-2.0                                        */
/* ****************************************************************************/
%macro create_postgres_etl(database=&database, table_name=,column_table=, key_list=) ;
	%local database mart_type table_name column_table key_list;

	filename codefile DISK "&code_file_path.";
	data _null_;
		file codefile mod;  
		put '%if %sysfunc(exist(&udmmart..' "&table_name" ')) %then %do;';
		put +3 '%let errFlag=0;';
		put +3 '%let nrows=0;';
		put +3 '%let dsid =%sysfunc(open(&udmmart..' "&table_name.));" ;
		put +3 '%let nrows=%sysfunc(attrn(&dsid,nlobs));';
		put +3 '%let dsid =%sysfunc(close(&dsid));';
	run;

	* full load ;
	%if &key_list = " " %then %do; 
		data _null_;
			set &column_table. end=last;
			where upcase(table_name)="&table_name.";
			file codefile mod;  
			if _n_=1 then do;
				* truncate table ;
				put +3 'proc sql noerrorstop;';
				put +6  'connect to &database. (&sql_passthru_connection.);';
				put +6  'execute (truncate table &dbschema..' "&table_name." ') by &database.;';
				put +6  'disconnect from &database.;';
				put +3 'quit;';
				put +3 '%err_check (Failed to truncate ' table_name ', ' table_name ');';

				* full load ;
				put +3 'proc append data=&udmmart..' table_name ' base=&trglib..' table_name '(';
				put +6  '%if &nrows ge &DB_BL_THRESHOLD. and &DB_BL_THRESHOLD. gt 0 %then %do;';
				put +9   '&DB_BL_OPTS.';
				put +6  '%end;';
				put +6  '%else %do;';
				put +9   '&DB_LD_OPTS.';
				put +6  '%end;';
				put +6  ') force;';
				put +3 'run;';
				put +3 '%err_check (Failed to append to ' table_name ', ' table_name ');';
			end;
		run;
	%end;


	%else %do; * incremental load;
		data _null_;
			set &column_table. end=last;
			length staging_table $32;
			where upcase(table_name)="&table_name.";
			file codefile mod;  
			staging_table=cats(substr(table_name,1,min(28,length(table_name))),"_tmp");
			if _n_=1 then do;
				put +3 '%if %sysfunc(exist(&tmplib..' staging_table ') ) %then %do;';
				put +6  'proc sql noerrorstop;';
				put +9   'drop table &tmplib..' staging_table ';';
				put +6  'quit;';
				put +3 '%end;';

				put +3 '%check_duplicate_from_source(table_nm=' table_name ', table_keys=%str(' &key_list '), out_table=work.' table_name ');';

				put +3 'data work.' staging_table '/view=work.' staging_table ';';
				put +6   'set work.' table_name ';';
			end;
			if index(lowcase(column_name),'_dttm_tz') then do;
				put +6 'if ' column_name  ' ne . then ' column_name  '= tzoneu2s(' column_name',&timeZone_Value.);';
			end;

			if last then do;
				put +3 'run;';
				put +3 '%err_check (Failed to add time zone adaptation :' staging_table ', ' table_name ');';

				/* Bulkload for large tables */
				put +3 '%if &errFlag = 0 %then %do;';
				put +6  '%if &nrows ge &DB_BL_THRESHOLD. and &DB_BL_THRESHOLD. gt 0 %then %do;';
				put +9   'data &tmplib..' staging_table ';';
				put +12   'set work.' staging_table ';';
				put +12   'stop;';
				put +9   'run;';
				put +9   'proc append data=work.' staging_table ' base=&tmplib..' staging_table '(&DB_BL_OPTS) force;';
				put +9   'run;';
				put +6  '%end;';
				put +6  '%else %do;';
				put +9   'data &tmplib..' staging_table ';';
				put +12   'set work.' staging_table ';';
				put +9   'run;';
				put +6  '%end;';
				put +6  '%err_check (Failed to upload to temp location in DB :' staging_table ', ' table_name ');';
				put +3 '%end;';
			end;
		run;
		data _null_;
			set &column_table. end=last;
			length staging_table $32;
			where upcase(table_name)="&table_name." and primary_key=1;
			file codefile mod;  
			staging_table=cats(substr(table_name,1,min(28,length(table_name))),"_tmp");
			if _n_=1 then do;
				put +3 '%if &errFlag = 0 %then %do;';
				put +6  'proc sql noerrorstop;';
				put +9   'connect to &database. (&sql_passthru_connection.);';
				put +9   'execute (merge into &dbschema..' table_name 'as b using &tmpdbschema..' staging_table 'as d on( ';
				put +12 @;
			end;	
			if mod(_n_,2)=0 then do; * start new line evetry 4 variables ;
				put;
				put +12 @;
			end;
			put 'b.' column_name '= d.' column_name @;
			if not last then put +(-1) ' and ' @;
			if last then do;
				put ')';
			end;	
		run;
		data _null_;
			set &column_table. end=last;
			length staging_table $32;
			where upcase(table_name)="&table_name." and primary_key ne 1;
			file codefile mod;  
			staging_table=cats(substr(table_name,1,min(28,length(table_name))),"_tmp");
			if _n_=1 then do;
				put +9 'when matched then  ';
				put +9 'update set ';
				put +12 @;
			end;
			if mod(_n_,2)=0 then do; * start new line evetry 4 variables ;
				put;
				put +12 @;
			end;
			put column_name '= d.' column_name @;
			if not last then put +(-1) ', ' @;
			if last then do;
				put;
			end;	
		run;
		data _null_;
			set &column_table. end=last;
			length staging_table $32;
			where upcase(table_name)="&table_name." ;
			file codefile mod;  
			staging_table=cats(substr(table_name,1,min(28,length(table_name))),"_tmp");
			if _n_=1 then do;
				key_condition=tranwrd(&key_list., ',', ' is NOT NULL and '); * key_list has quoted content;
				put +9 'when not matched and ' key_condition 'is NOT NULL then insert (';
				put +12 @;
			end;
			if mod(_n_,4)=0 then do; * start new line evetry 4 variables ;
				put;
				put +12 @;
			end;
			put column_name @;
			if not last then put +(-1) ', ' @;
		run;
		data _null_;
			set &column_table. end=last;
			length staging_table $32;
			where upcase(table_name)="&table_name." ;
			file codefile mod;  
			staging_table=cats(substr(table_name,1,min(28,length(table_name))),"_tmp");
			if _n_=1 then do;
				put +9 ') values ( ';
				put +12 @;
			end;
			if mod(_n_,4)=0 then do; * start new line evetry 4 variables ;
				put;
				put +12 @;
			end;
			put 'd.' column_name @;
			if not last then put +(-1) ', ' @;
			if last then do;
				put       ' );) by &database.;';
				put +9   'disconnect from &database.;';
				put +6  'quit;';
				put +6  '%err_check (Failed to Update/Insert into  :' staging_table ', ' table_name ', err_macro=SYSDBRC);';
				put +3 '%end;';

				put +3 '%if %sysfunc(exist(&tmplib..' staging_table ')) %then %do;';
				put +6  'proc sql noerrorstop;';
				put +9   'drop table &tmplib..' staging_table ';';
				put +6  'quit;';
				put +3 '%end;';
			end;
		run;
	%end;

	* clean up if all went well;
	data _null_;
		file codefile mod;  
		put +3 '%if &errFlag = 0 %then %do;';
		put +6  'proc sql noerrorstop;';
		put +9   'drop table &udmmart..' "&table_name" ';';
		put +9   'drop table work.' "&table_name" ';';
		put +6  'quit;';
		put +3 '%end;';
		put +3 '%else %do;';
		put +6  '%put %sysfunc(datetime(),E8601DT25.) --- &UDM_ErrMsg;';
		put +3 '%end;';
		put +3 '%put %sysfunc(datetime(),E8601DT25.) --- Processing table ' "&table_name." ';';
		put +3 '%put------------------------------------------------------------------;';
		put '%end;';
	run;

	filename codefile;

%mend create_postgres_etl;
