spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://db:5432/demo
spring.datasource.username=demo
spring.datasource.password=demo
spring.datasource.hikari.maximum-pool-size=5
logging.level.root=INFO
#logging.level.com.example.connectorservice=DEBUG